name: Create and Cache ML Model for Predicting GitHub Issue and PR Labels

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  create-model-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Capture repository state
        id: capture-repo-state
        run: |
          echo "::group::Capture repository state"

          owner=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f1)
          repo=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)
          date=$(date -u +%Y-%m-%d)

          echo "owner=$owner"
          echo "repo=$repo"
          echo "date=$date"

          newest_issue=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues?state=all&sort=created&per_page=1" \
            | jq 'try if .[0] then .[0].number // 0 else 0 end catch 0'

          echo "newest_issue=$newest_issue"
          echo "::endgroup::"

          echo "{ \"owner\": \"$owner\", \"repo\": \"$repo\", \"date\": \"$date\", \"newest_issue\": $newest_issue }" > github-ml-labeler-state.json

      - name: Cache the github-ml-labeler-state.json file
        id: cache-repo-state
        uses: actions/cache@v4
        with:
          path: github-ml-labeler-state.json
          key: "github-ml-labeler"
