name: "Labeler: Label Pull Request"

on:
  pull_request:
    types: [opened, edited, synchronize, unlabeled]

  workflow_call:
    inputs:
      number:
        description: "Issue Number"
        type: number
        required: true
      label_prefix:
        description: "Label Prefix"
        type: string
        required: true
      threshold:
        description: "The minimum confidence score for a label prediction"
        type: number
        default: 0.75
        required: true
      default_label:
        description: "Default Label (leave blank for no default label)"
        type: string
      model_repo:
        description: "The org/repo to use for the cached model (defaults to current repository)"
        type: string

  workflow_dispatch:
    inputs:
      org_repo:
        description: "The org/repo to use (defaults to current repository)"
        type: string
      github_token:
        description: "The GitHub token (defaults to action token)"
        type: string
      number:
        description: "Pull Request Number"
        required: true
      label_prefix:
        description: "Label Prefix"
        default: "area-"
        required: true
      threshold:
        description: "The minimum confidence score for a label prediction"
        type: number
        default: 0.75
        required: true
      default_label:
        description: "Default Label"
        default: "needs-area-label"
      model_repo:
        description: "The org/repo to use for the cached model (defaults to current repository)"
        type: string

permissions:
  pull-requests: write

jobs:
  label-pull:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: "Check out the '${{ github.action_repository }}' repo"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.action_repository }}

      # Restore cache after checkout to ensure files aren't cleaned or removed
      - name: "Restore pull-model.zip from 'github-ml-labeler/${{ inputs.model_repo || github.repository }}/model-pulls'"
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/pull-model.zip
          key: github-ml-labeler/${{ inputs.model_repo || github.repository }}/model-pulls
          fail-on-cache-miss: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: "Run LabelPredictor"
        run: |
          dotnet run --project src/LabelPredictor -- \
            "${{ inputs.org_repo || github.repository }}" \
            "${{ inputs.github_token || secrets.GITHUB_TOKEN }}" \
            --pull-model labeler-cache/pull-model.zip \
            --pull ${{ fromJSON(inputs.number || github.event.number) }} \
            --label-prefix "${{ inputs.label_prefix || 'area-' }}" \
            --threshold ${{ fromJSON( inputs.threshold || 0.75 ) }} \
            --default-label "${{ inputs.default_label || 'needs-area-label' }}"
