name: "Labeler: Model Issues"

on:
  schedule:
    - cron: "34 3 * * 3"

  workflow_dispatch:

jobs:
  model-issues:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-data.tsv
          key: github-ml-labeler/download-issues

      - name: Run ModelCreator
        if: steps.restore-cache.outputs.cache-hit == 'true'
        run: |
          cat labeler-cache/issue-data.tsv
          cd src/ModelCreator
          dotnet run -- --issue-data ../../labeler-cache/issue-data.tsv --issue-model ../labeler-cache/issue-model.zip

      - name: Save model to cache
        if: steps.restore-cache.outputs.cache-hit == 'true'
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-model.zip
          key: github-ml-labeler/model-issues

      - name: Handle cache miss
        id: handle-cache-miss
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss: 'labeler-cache/issue-data.tsv' not found in 'github-ml-labeler/download-issues' cache"
