name: "Labeler: Label Issue"

on:
  issues:
    types: [opened, edited, transferred, unlabeled]

  workflow_dispatch:
    inputs:
      org_repo:
        description: "The org/repo to use (defaults to current repository)"
        type: string
      github_token:
        description: "The GitHub token (defaults to action token)"
        type: string
      number:
        description: "Issue Number"
        required: true
      label_prefix:
        description: "Label Prefix"
        default: "area-"
        required: true
      default_label:
        description: "Default Label"
        default: "needs-area-label"
        required: true

permissions:
  issues: write

jobs:
  label-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      # Restore cache after checkout to ensure files aren't cleaned or removed
      - name: "Restore issue-model.zip from cache"
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-model.zip
          key: github-ml-labeler/${{ inputs.org_repo || github.repository }}/model-issues
          fail-on-cache-miss: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: "Run LabelPredictor"
        run: |
          dotnet run --project src/LabelPredictor -- \
            "${{ inputs.org_repo || github.repository }}" \
            "${{ inputs.github_token || secrets.GITHUB_TOKEN }}" \
            --issue-model labeler-cache/issue-model.zip \
            --issue ${{ fromJSON(inputs.number || github.event.number) }} \
            --label-prefix "${{ inputs.label_prefix || 'area-' }}" \
            --default-label "${{ inputs.default_label || 'needs-area-label' }}" \
            --threshold 0.75
