name: "Labeler: Model Issues"

on:
  schedule:
    - cron: '0 2 5 * *' # 02:00 UTC on the 5th day of the month

  workflow_call:
    inputs:
      data_repo:
        description: "The org/repo to load issue data from (defaults to current repository)"
        type: string

  workflow_dispatch:
    inputs:
      data_repo:
        description: "The org/repo to load issue data from (defaults to current repository)"
        type: string
      model_repo:
        description: "The org/repo to cache the issue model for (defaults to current repository)"
        type: string

jobs:
  model-issues:
    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
      - name: "Check out the '${{ github.action_repository }}' repo"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.action_repository }}

      # Restore cache after checkout to ensure files aren't cleaned or removed
      - name: "Restore issue-data.tsv from 'github-ml-labeler/${{ inputs.data_repo || github.repository }}/download-issues'"
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-data.tsv
          key: github-ml-labeler/${{ inputs.data_repo || github.repository }}/download-issues
          fail-on-cache-miss: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: "Run ModelCreator"
        run: |
          dotnet run --project src/ModelCreator -- \
            --issue-data labeler-cache/issue-data.tsv \
            --issue-model labeler-cache/issue-model.zip

      - name: "Cache issue-model.zip into 'github-ml-labeler/${{ inputs.model_repo || github.repository }}/model-issues'"
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-model.zip
          key: github-ml-labeler/${{ inputs.model_repo || github.repository }}/model-issues
