name: "Labeler: Model Issues"

on:
  schedule:
    - cron: "34 3 * * 3"

  workflow_dispatch:

jobs:
  model-issues:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Restore cache after checkout to ensure files aren't cleaned or removed
      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-data.tsv
          key: github-ml-labeler/download-issues
          fail-on-cache-miss: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run ModelCreator
        run: |
          cd src/ModelCreator
          dotnet run -- --issue-data ../../labeler-cache/issue-data.tsv --issue-model ../labeler-cache/issue-model.zip

      - name: Save model to cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-model.zip
          key: github-ml-labeler/model-issues
